Translate domain pages into Russian
effector/effector pull request #1053
Opened 2024-02-28 10:47 UTC by mitapfer

2024-03-08 05:40 UTC, igorkamyshev requested changes
Спасибо за пиар 🙏

Принес несколько замечаний:
🤓 — совет / вопрос
🚧 — потенциальная проблема
🚨 — опасность / баг

Плюс, попрошу документы пропустить через какой-то спелл-чекер, чтобы избавить их от опечаток.

2024-03-08 05:40 UTC, igorkamyshev commented on documentation/pnpm-lock.yaml
> +lockfileVersion: 5.4
🚨 почти уверен, что это изменение не должно быть в этом пиаре. Можем убрать изменения в этом файле из пиара?

2024-03-08 05:40 UTC, igorkamyshev commented on documentation/src/content/docs/ru/api/effector/Domain.md
> +_Domain (домен)_ - это способ группировки и применения массовых обработок к юнитам.
🤓 кажется, как-то не по-русски вышло — «применение массовых обработок к юнитам». Может быть, что-то типо «массовой обработки юнитов»?

2024-03-08 05:40 UTC, igorkamyshev commented on documentation/src/content/docs/ru/api/effector/Domain.md
> +Домен может подписываться на событие, эффект, стор или вложенный домен, созданный с помощью методов `onCreateEvent`, `onCreateStore`, `onCreateEffect`, `onCreateDomain`.
🚨 это фактическая ошибка. Домен не может никуда подписываться.

2024-03-08 05:40 UTC, igorkamyshev commented on documentation/src/content/docs/ru/api/effector/Domain.md
> +- Когда любой из юнитов создается внутри домена, он появляется в наборе с именем типа (сторы, события, домены, эффекты) в порядке создания.
🚧 кажется, то что в скобочках лучше не переводить. Это же имена полей в объекте.

2024-03-08 05:40 UTC, igorkamyshev commented on documentation/src/content/docs/ru/api/effector/Domain.md
> +Алиас для [domain.createEvent](/ru/api/effector/Domain#createevent-name)
🤓 не уверен, насколько «алиас» хорошо подходит для русского языка. Псевдоним?

2024-03-08 05:40 UTC, igorkamyshev commented on documentation/src/content/docs/ru/api/effector/Domain.md
> +- Функция переданная в `onCreateEvent` вызывается каждый раз, когда создается новое события в `domain`
```suggestion
- Функция переданная в `onCreateEvent` вызывается каждый раз, когда создается новое событие в `domain`
```

2024-03-08 05:40 UTC, igorkamyshev commented on documentation/src/content/docs/ru/api/effector/createDomain.md
> +const domain = createDomain(); // безимянный домен
```suggestion
const domain = createDomain(); // безымянный домен
```

2024-12-17 17:15 UTC, sergeysova approved these changes

2025-01-08 03:35 UTC, zerobias approved these changes

2025-01-08 03:36 UTC, merged