Аix useEvent typings for void payload
effector/effector pull request #501
Opened 2021-06-23 04:48 UTC by igorkamyshev

Hello! My team-mate found `useEvent` types issue and I wanna to fix it. I am not so good at types writing, so please review my PR and give me feedback.

Fix #500

2021-06-23 18:28 UTC, zerobias requested changes
Current tests are passed, so it's probably ok, but its better to add new type tests with your case to be sure that it will work as expected. Tests for useEvent are [here](https://github.com/effector/effector/blob/master/src/types/__tests__/effector-react/effectorReact.test.tsx#L55).



Contribution guide for type tests: https://github.com/effector/effector/blob/master/CONTRIBUTING.md#type-tests

Feel free to write to me if you have any questions

2021-06-24 05:09 UTC, igorkamyshev commented
Sorry, you are right. Fixed ☑️

2021-06-26 09:14 UTC, zerobias approved these changes

2021-06-26 09:14 UTC, zerobias commented
Great, thanks! 👍

2021-06-26 09:14 UTC, merged