Add russian translation
effector/effector pull request #816
Opened 2022-11-26 16:36 UTC by Tsyklop

2022-11-26 18:48 UTC, sergeysova approved these changes

2022-11-26 23:01 UTC, Minhir commented
Надо аккуратно проверить весь текст. Сейчас несовпадения в терминологии вроде "стор"/"магазин" и т.д.

2022-11-27 03:00 UTC, igorkamyshev requested changes

2022-11-27 03:00 UTC, igorkamyshev commented on website/client/i18n/ru/docusaurus-plugin-content-docs/current/api/effector/split.md
> +Строка-возвращающая функция, которая будет вызвана со значением из `source` для выбора случая по его имени. Размещается непосредственно в поле `match`, [должно быть **чистым**](../../glossary.md#puri
Этот перевод выполнен машиной. Если переводить, то вручную.

2022-11-27 03:37 UTC, AlexandrHoroshih requested changes
В ПР есть изменения в англоязычной версии документации, их надо убрать, а перевод перенести

2022-11-28 05:46 UTC, igorkamyshev requested changes
Это машинный перевод. Это нельзя мерджить в мастер.

2022-11-28 05:59 UTC, igorkamyshev requested changes
Я прошу прощения за вероятно токсичное ревью, мне показалось важным указать на все проблемы текущего перевода.

Пиар закрываю, пожалуйста, примите замечания к сведению и исправьте их.

Если вам требуется перевод сайта на русский такого качества, рекомендую поставить браузерное расщирение для Гугл Переводчика.

2022-11-28 05:59 UTC, igorkamyshev commented on website/client/i18n/ru/docusaurus-plugin-content-docs/current/api/effector/Domain.md
> +Он полезен при логировании или других побочных эффектах.
Предложение не согласовано, так не говорят.

2022-11-28 05:59 UTC, igorkamyshev commented on website/client/i18n/ru/docusaurus-plugin-content-docs/current/api/effector/Domain.md
> +- Когда внутри домена создаются юниты любого типа, они появляются в наборе с именем типа (сторы, события, домены, эффекты) в том же порядке, в котором создавались
Каком «наборе»? Это же просто калька с `set`

2022-11-28 05:59 UTC, igorkamyshev commented on website/client/i18n/ru/docusaurus-plugin-content-docs/current/api/effector/Domain.md
> +// => новый эффект создан
Нет, выше лог на английском. С чего бы тут будет лог на русском? Код не согласован с результатом.

2022-11-28 05:59 UTC, igorkamyshev commented on website/client/i18n/ru/docusaurus-plugin-content-docs/current/api/effector/Domain.md
> +// => новый домен создан
Опять

2022-11-28 05:59 UTC, igorkamyshev commented on website/client/i18n/ru/docusaurus-plugin-content-docs/current/api/effector/attach.md
> +Примеры использования: декларативный способ передачи значений из сторов в эффекты и предварительная обработка аргументов.
Это не примеры использования. Use cases так не переводится.

2022-11-28 05:59 UTC, igorkamyshev commented on website/client/i18n/ru/docusaurus-plugin-content-docs/current/api/effector/attach.md
> +Создайте эффект, который будет вызывать заданный эффект со значениями из хранилищ `source`.
Почему везде инфинитив, а тут повелительное наклонение? Перевод не согласован.

2022-11-28 05:59 UTC, igorkamyshev commented on website/client/i18n/ru/docusaurus-plugin-content-docs/current/api/effector/attach.md
> +Создайте эффект, который будет вызывать асинхронную функцию со значениями из хранилищ `source`.
Снова.

2022-11-28 05:59 UTC, igorkamyshev commented on website/client/i18n/ru/docusaurus-plugin-content-docs/current/api/effector/attach.md
> +Создайте эффект, который вызовет заданный эффект, преобразовав параметры с помощью функции `mapParams`.
Снова

2022-11-28 05:59 UTC, igorkamyshev commented on website/client/i18n/ru/docusaurus-plugin-content-docs/current/api/effector/attach.md
> +Если `mapParams` выдаст ошибку, это вызовет событие `fail` и вложенный `effect` не будет вызван вообще
throw — это не выдаст, фактическая ошибка

2022-11-28 05:59 UTC, igorkamyshev commented on website/client/i18n/ru/docusaurus-plugin-content-docs/current/api/effector/attach.md
> +Создайте эффект, который будет вызывать `effect` с параметрами как есть. Это позволяет создавать отдельные эффекты с общим поведением.
Снова повелительное наклонение. Почему?

2022-11-28 05:59 UTC, igorkamyshev commented on website/client/i18n/ru/docusaurus-plugin-content-docs/current/api/effector/split.md
> +Выбирает один из случаев по заданным условиям. Он "разбивает" исходный блок на несколько событий, которые срабатывают, когда полезная нагрузка соответствует их условиям. Работает как сопоставление ша
splits тут играет с именем метода. Утерян смысл.

Что за блок? Это снова машинный перевод слова unit.

Какая полезная нагрузка? Это снова машинный перевод слова payload.

Какие внешние хранилища? Хорошо не магазины. Это снова машинный перевод.

2022-11-28 05:59 UTC, igorkamyshev commented on website/client/i18n/ru/docusaurus-plugin-content-docs/current/api/effector/split.md
> +Режим, в котором целевой случай выбирается по имени его поля. Кейс может быть выбран из данных в `source` с помощью [case function](./split.md#case-function) или из внешнего [case store](./split.md#c
Почему тут перемешан русский и английский? case store? тогда уж магазин чехлов

2022-11-28 05:59 UTC, igorkamyshev commented on website/client/i18n/ru/docusaurus-plugin-content-docs/current/api/effector/split.md
> +Если одно из полей получило `true` от значения стора или возврата функции, то данные из `source` будут отправлены в соответствующий `cases[fieldName]` (если таковой имеется), если ни одно из полей не
предложение не согласовано

2022-11-28 05:59 UTC, igorkamyshev commented on website/client/i18n/ru/docusaurus-plugin-content-docs/current/api/effector/split.md
> +Булево хранилище, указывающее, следует ли выбрать конкретный случай или попробовать следующий. Размещается в полях объекта `match`, может смешиваться с [matcher functions](./split.md#matcher-function
Снова термин переведен иначе. То магазин, то стор, то хранилище.

2022-11-28 05:59 UTC, igorkamyshev commented on website/client/i18n/ru/docusaurus-plugin-content-docs/current/api/effector/split.md
> +Булево хранилище, указывающее, следует ли выбрать конкретный случай или попробовать следующий. Размещается в полях объекта `match`, может смешиваться с [matcher functions](./split.md#matcher-function
А matcher function почему-то вообще не переведено.

2022-11-28 05:59 UTC, igorkamyshev commented on website/client/i18n/ru/docusaurus-plugin-content-docs/current/api/effector/split.md
> +Функция возвращающая `boolean`, указывающая, следует ли выбрать конкретный случай или попробовать следующий. Размещается в полях объекта `match`, может смешиваться с [matcher stores](./split.md#match
Снова. Раньше было «булево», теперь без перевода. matcher store снова не перведен.

2022-11-28 05:59 UTC, igorkamyshev commented on website/client/i18n/ru/docusaurus-plugin-content-docs/current/api/effector/split.md
> +Case store, case function и matcher store поддерживаются начиная с версии effector 21.8.0
se store, case function и matcher store — тут только одна русская буква. Это перевод?

2022-11-28 05:59 UTC, igorkamyshev commented on website/client/i18n/ru/docusaurus-plugin-content-docs/current/api/effector/split.md
> +Вы также можете напрямую обращаться к стору api:
Это предложение не имеет смысла.

2022-11-28 05:59 UTC, igorkamyshev commented on website/client/i18n/ru/docusaurus-plugin-content-docs/current/api/effector/split.md
> +2. `match` (_Object_): Схема случаев, в которой в качестве ключей используются имена результирующих событий, а в качестве функции соответствия*((value) => Boolean)*.
Схема?

2022-11-28 05:59 UTC, igorkamyshev commented on website/client/i18n/ru/docusaurus-plugin-content-docs/current/introduction/community.md
> +Каждый член команды ежедневно пользуется библиотекой как пользователь и старается улучшить пользовательский опыт как основной член команды.
Это калька с английского, на русском так не говорят.

2022-11-28 05:59 UTC, igorkamyshev commented on website/client/i18n/ru/docusaurus-plugin-content-docs/current/introduction/community.md
> +Игорь работает над [Farfetched](https://farfetched.pages.dev) продвинутым инструментом для сбора данных.
Ну ведь достаточно прочитать вслух это предложение, чтобы понять что оно не должно существовать. Это калька с английского.

2022-11-28 05:59 UTC, igorkamyshev commented on website/client/i18n/ru/docusaurus-plugin-content-docs/current/introduction/community.md
> +Игорь сделал [eslint-plugin-effector](https://eslint.effector.dev) и просмотрел многие PR и проблемы пакетов effector и экосистемы.
ПРОБЛЕМЫ? Ну камон.

2022-11-28 05:59 UTC, closed without merging