EFX-142: add Companies section on Landing page
effector/effector pull request #954
Opened 2023-07-26 20:54 UTC by ainursharaev

## Visual references

<img width="1379" alt="image" src="https://github.com/effector/effector/assets/33234903/fb9e7ba0-8abc-4687-904f-0ec54ee5c923">
<img width="764" alt="image" src="https://github.com/effector/effector/assets/33234903/c7d2d859-8710-495b-b60d-65fa62ede883">
<img width="1744" alt="image" src="https://github.com/effector/effector/assets/33234903/8f4b5de8-cb3b-4728-a08f-725ba19a23bd">
<img width="372" alt="image" src="https://github.com/effector/effector/assets/33234903/2e419544-00a3-414c-a9f4-33b30b730c07">

2023-07-26 20:56 UTC, sergeysova commented on beta/src/components/Landing/Companies.astro
> +  <header>
```suggestion
  <h3>
```

2023-07-26 20:59 UTC, sergeysova requested changes

2023-07-26 20:59 UTC, sergeysova commented on beta/src/components/Landing/Companies.astro
> +          key={i}
Are you need key in Astro components?

2023-07-26 20:59 UTC, sergeysova commented on beta/src/components/Landing/Companies.astro
> +    --maxWidth: 90vw;
Sometimes ‘param-case’ sometimes ‘camelCase’

2023-07-31 10:11 UTC, ainursharaev commented on beta/src/components/Landing/Companies.astro
> +          key={i}
good catch, didn't know that 👍

2023-07-31 10:14 UTC, ainursharaev commented on beta/src/components/Landing/Companies.astro
> +  <header>
done ✅

2023-07-31 10:14 UTC, ainursharaev commented on beta/src/components/Landing/Companies.astro
> +          key={i}
removed ✅

2023-07-31 10:15 UTC, ainursharaev commented on beta/src/components/Landing/Companies.astro
> +    --maxWidth: 90vw;
changed ✅

2023-08-01 09:32 UTC, sergeysova commented
@ainursharaev Thank you!

2023-08-01 09:32 UTC, merged